version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.10
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.20.0
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
  - dependency-name: esbuild
    versions:
    - 0.10.0
    - 0.11.0
    - 0.11.1
    - 0.11.2
    - 0.11.3
    - 0.11.5
    - 0.11.6
    - 0.8.50
    - 0.8.57
    - 0.9.0
    - 0.9.2
    - 0.9.3
    - 0.9.4
    - 0.9.6
    - 0.9.7
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: husky
    versions:
    - 5.1.3
    - 5.2.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.15
    - 7.12.17
    - 7.13.10
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: xdm
    versions:
    - 1.5.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.17
    - 7.13.0
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: "@babel/plugin-proposal-private-methods"
    versions:
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
    - 7.13.0
  - dependency-name: sass
    versions:
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.6
    - 1.3.7
    - 1.3.8
  - dependency-name: "@types/prismjs"
    versions:
    - 1.16.3
  - dependency-name: "@preconstruct/cli"
    versions:
    - 2.0.3
    - 2.0.4
  - dependency-name: "@changesets/cli"
    versions:
    - 2.14.1
  - dependency-name: css-loader
    versions:
    - 5.0.2
  - dependency-name: sass-loader
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: postcss-loader
    versions:
    - 5.0.0
  - dependency-name: pino-pretty
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: eslint
    versions:
    - 7.19.0
  - dependency-name: ts-jest
    versions:
    - 26.5.0
  - dependency-name: "@types/yargs"
    versions:
    - 16.0.0
  - dependency-name: commander
    versions:
    - 7.0.0
