nodeLinker: node-modules

packageExtensions:
  ts-jest@*:
    dependencies:
      jest-config: 25.x

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.0.0-rc.36.js
