packageExtensions:
  ts-jest@*:
    dependencies:
      jest-config: 25.x

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-rc.js

nodeLinker: node-modules
